// import clientPromise from '@/utils/mongodb';
import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import dbConnect from "../utils/dbConnect";
import LyricModel from "@/models/LyricSchema";

export async function getServerSideProps(context) {

    await dbConnect();
    const data = await LyricModel.findById("65b795bc6104d74ab08ccd44");
    console.log("data server", data);
    return {
      props: { data: JSON.parse(JSON.stringify(data)) },
    };
  } catch (error) {
    console.error("Error fetching data:", error);
    return { props: { data: [] } };
  }
}

export default function Context({ data }) {
  // console.log('data', data)
  //     const router = useRouter()
  //     const handlerSelect = (id) => {
  //   const songId = id.toString();
  //   router.push(`/${songId}`);
  // }
  //     console.log('data :>> ', data);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ul>
        {data &&
          data.map((song, index) => (
            <div key={song._id}>
              <h3 onClick={() => handlerSelect(song._id)}>
                {song.lyric} by {song.author}
              </h3>
            </div>
          ))}
      </ul>
    </>
  );
}
