// import clientPromise from '@/utils/mongodb';
import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import dbConnect from "../utils/dbConnect";

import dbConnection from "../../lib/dbConnection";
import { LyricModel } from "@/models/Schemas";
import styles from "@/styles/context.module.css";
import AppBar from "./component/AppBar";
import { useSession } from "next-auth/react";

export async function getServerSideProps(context) {
  try {
    await dbConnection();
    const data = await LyricModel.find({});
    console.log("data server", data);
    return {
      props: { data: JSON.parse(JSON.stringify(data)) },
    };
  } catch (error) {
    console.error("Error fetching data:", error);
    return { props: { data: [] } };
  }
}

export default function Context({ data }) {
  console.log("data client", data);
  const { data: session } = useSession();
  const user = session?.user;
  console.log("user :>> ", user);
  const router = useRouter();
  const handlerSelect = (id) => {
    const songId = id.toString();
    router.push(`/${songId}`);
  };
  console.log("data :>> ", data);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div
        style={{
          backgroundImage:
            "url('https://res.cloudinary.com/dqgvmwnpl/image/upload/v1708077101/audio-7276511_1280_t63a2m.jpg')",
          backgroundSize: "cover",
          minHeight: "100vh",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          // zIndex: "-1",
          position: "relative",
        }}
      >
        {/* <h1>Welcome to My Next.js App!</h1> */}
      {/* </div> */}

      <div className={styles.songListContainer}>
        <h1 className={styles.title}>SONGS THAT TOUCH YOUR SOUL </h1>
        <ul className={styles.songList}>
          {data &&
            data.map((song, index) => (
              <li
                key={song._id}
                className={styles.songItem}
                onClick={() => handlerSelect(song._id)}
              >
                <span className={styles.songTitle}>{song.lyric}</span> by{" "}
                <span className={styles.authorName}>{song.author}</span>
              </li>
            ))}
        </ul>
        <img
          src="https://res.cloudinary.com/dqgvmwnpl/image/upload/v1708077101/audio-7276511_1280_t63a2m.jpg"
          alt=""
        />
      </div>
    </>
  );
}
