import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
// import styles from "@/styles/Home.module.css";
import Providers from "./component/Providers";
import AppBar from "./component/AppBar";
import { useSession } from "next-auth/react";
import { useRouter } from "next/router";
import styles from "@/styles/landing.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { data: session } = useSession();
  const router = useRouter();

  const user = session?.user;
  console.log("user :>> ", user);

  const handleLoginClick = () => {
    router.push(`/login`);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Providers>
          <AppBar />

          {session ? (
            <div>Welcome, {session.user.name}!</div>
          ) : (
            <div>Please sign in.</div>
          )}
        </Providers>
        <div className={styles.container}>
          <div className={styles.textContainer}>
            <h4 className={styles.quatetext}>
              Rhythms of Learning: Where Music Meets English Mastery!
            </h4>
            <p className={styles.text}>
              A unique e-learning experience where the soulful world of music
              meets the mastery of English. Immerse yourself in captivating
              melodies and lyrics that not only touch your heart but also
              enhance your language skills. Perfect for music lovers and
              language learners alike, this program turns each song into a step
              towards fluency.
            </p>
          </div>
          <div className={styles.mediaContainer}>
            <div className={styles.videoContainer}>
              <img
                className={styles.bg}
                src="https://res.cloudinary.com/dqgvmwnpl/image/upload/v1706104998/E-Learning/concept-eternal-theme-about-eternity-music-musical-instruments-good-mood-ascended-aspiration-action-treble-clef-sheet-music_771426-4115_zwn40l.avif"
                alt="Description"
              />
              <div className={styles.viewport}>
                <h2 className={styles.logo}>Songs that Touch Your Soul </h2>
              </div>

              <video className={styles.video} autoPlay loop muted>
                <source
                  src="https://res.cloudinary.com/dqgvmwnpl/video/upload/v1706093596/E-Learning/163355_720p_n7m1oe.mp4"
                  type="video/mp4"
                />
              </video>
            </div>

            <div className={styles.darkOverlay}></div>
          </div>

          <div className={styles.buttonContainer}>
            {/* <button onClick={handleLoginClick}>GET STARTED</button>  */}

            <p className={styles.text}>GET STARTED</p>
            <svg
              onClick={handleLoginClick}
              className={styles.svgStyle}
              width="25%"
              height="25%"
              viewBox="0 0 100 100"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <rect
                className={styles.buttonSides}
                x="5.04999"
                y="51"
                width="90.62"
                height="8"
              />
              <rect
                className={styles.buttonSides}
                width="57"
                height="57"
                rx="8"
                transform="matrix(0.866025 -0.5 0.866025 0.5 1 59)"
              />
              <g clip-path="url(#clip0_106_11)">
                <rect
                  className={styles.buttonTop}
                  width="57"
                  height="57"
                  rx="8"
                  transform="matrix(0.866025 -0.5 0.866025 0.5 1 51)"
                />
                <path
                  className={styles.buttonSidesplaySides}
                  d="M64.2199 42.5L55.4353 61.4282L31.4353 47.5718L64.2199 42.5Z"
                  fill="white"
                />
                <g className={styles.glowAll} filter="url(#filter0_d_106_11)">
                  <path
                    d="M64.2199 42.5L55.4353 61.4282L31.4353 47.5718L64.2199 42.5Z"
                    fill="white"
                  />
                </g>
                <g
                  className={styles.glowMe}
                  opacity="0.5"
                  filter="url(#filter1_f_106_11)"
                >
                  <path
                    d="M73.0478 36.9032L58.6665 67.8905L19.3761 45.2062L73.0478 36.9032Z"
                    fill="white"
                  />
                </g>
              </g>
              <path
                className={styles.glowMe}
                opacity="0.5"
                d="M64 43L32 47.8L32 8L64 8L64 43Z"
                fill="url(#paint0_linear_106_11)"
              />
              <defs>
                <filter
                  id="filter0_d_106_11"
                  x="23.4353"
                  y="34.5"
                  width="48.7846"
                  height="34.9282"
                  filterUnits="userSpaceOnUse"
                  color-interpolation-filters="sRGB"
                >
                  <feFlood flood-opacity="0" result="BackgroundImageFix" />
                  <feColorMatrix
                    in="SourceAlpha"
                    type="matrix"
                    values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
                    result="hardAlpha"
                  />
                  <feOffset />
                  <feGaussianBlur stdDeviation="4" />
                  <feComposite in2="hardAlpha" operator="out" />
                  <feColorMatrix
                    type="matrix"
                    values="0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0"
                  />
                  <feBlend
                    mode="normal"
                    in2="BackgroundImageFix"
                    result="effect1_dropShadow_106_11"
                  />
                  <feBlend
                    mode="normal"
                    in="SourceGraphic"
                    in2="effect1_dropShadow_106_11"
                    result="shape"
                  />
                </filter>
                <filter
                  id="filter1_f_106_11"
                  x="3.37613"
                  y="20.9032"
                  width="85.6716"
                  height="62.9873"
                  filterUnits="userSpaceOnUse"
                  color-interpolation-filters="sRGB"
                >
                  <feFlood flood-opacity="0" result="BackgroundImageFix" />
                  <feBlend
                    mode="normal"
                    in="SourceGraphic"
                    in2="BackgroundImageFix"
                    result="shape"
                  />
                  <feGaussianBlur
                    stdDeviation="8"
                    result="effect1_foregroundBlur_106_11"
                  />
                </filter>
                <linearGradient
                  id="paint0_linear_106_11"
                  x1="47"
                  y1="48"
                  x2="47"
                  y2="8"
                  gradientUnits="userSpaceOnUse"
                >
                  <stop stop-color="white" />
                  <stop offset="1" stop-color="white" stop-opacity="0" />
                </linearGradient>
                <clipPath id="clip0_106_11">
                  <rect
                    width="57"
                    height="57"
                    rx="8"
                    transform="matrix(0.866025 -0.5 0.866025 0.5 1 51)"
                    fill="white"
                  />
                </clipPath>
              </defs>
            </svg>
          </div>
        </div>
      </main>
    </>
  );
}
