import Head from "next/head";
import React from "react";
// import styles from "@/styles/landing.module.css";
import { useRouter } from "next/router";

export default function LandingPage() {
   const router = useRouter();
 

  const handleLoginClick = () => {
    router.push(`/login`);
  };



  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
    </>
  );
}
