import { signIn, useSession } from "next-auth/react";
import Head from "next/head";
import React, { useState } from "react";
import styles from "@/styles/login.module.css";

export default function Login() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [signUp,setSignUp]=useState(false)
  const [confirmPassword, setConfirmPassword] = useState("");

 

  const toggleLoginClick = () => {
    setSignUp(!signUp)
  };

  const handleSignIn = async (e) => {
    e.preventDefault();

    signIn("credentials", {
      email,
      password,
      callbackUrl: `${window.location.origin}/landing`,
    });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <div className={styles.formContainer}>
          <h2>Welcome Back 👋</h2>
          <p>
            Every dream begins with a step forward; every achievement, with the
            courage to start. Dare to dream, dare to act, and watch the
            impossible become your reality
          </p>
          {signUp ? (
  <form >
    {/* Форма регистрации */}
    <label htmlFor="email">Email
      <input type="email" placeholder="email" value={email} onChange={(e) => setEmail(e.target.value)} />
    </label>
    <label htmlFor="password">Password
      <input type="password" placeholder="password" value={password} onChange={(e) => setPassword(e.target.value)} />
    </label>
    <label htmlFor="confirmPassword">Confirm Password
      <input type="password" placeholder="confirm password"  onChange={(e) => setConfirmPassword(e.target.value)} />
    </label>
    <button type="submit">Sign up</button>
  </form>
) : (
  <form onSubmit={handleSignIn}>
    {/* Форма входа */}
    <label htmlFor="email">Email
      <input type="email" placeholder="email" value={email} onChange={(e) => setEmail(e.target.value)} />
    </label>
    <label htmlFor="password">Password
      <input type="password" placeholder="password" value={password} onChange={(e) => setPassword(e.target.value)} />
    </label>
    <p className={styles.forgotPassword}>Forgot Password?</p>
    <button type="submit">Sign in</button>
    <p>or</p>
    <button className={styles.googleBtn} onClick={() => signIn("google")}>
      {/* Google Sign-In Button */}
    </button>
  </form>
)}
          {/* {signUp && (
            <form >
            <label htmlFor="">
              Email{" "}
              <input
                type="email"
                placeholder="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
              />
            </label>
            <label htmlFor="">
              Password{" "}
              <input
                type="text"
                placeholder="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
              />
            </label>
            <p className={styles.forgotPassword}>Forgot Password?</p>
            <button type="submit">Sign in</button>
          </form>
          )}:(
          <form onSubmit={handleSignIn}>
            <label htmlFor="">
              Email{" "}
              <input
                type="email"
                placeholder="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
              />
            </label>
            <label htmlFor="">
              Password{" "}
              <input
                type="text"
                placeholder="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
              />
            </label>
            <p className={styles.forgotPassword}>Forgot Password?</p>
            <button type="submit">Sign in</button>
          </form> */}

          <p>or</p>
          <button className={styles.googleBtn} onClick={() => signIn("google")}>
            <img
              src="https://res.cloudinary.com/dqgvmwnpl/image/upload/v1706279633/E-Learning/7123025_logo_google_g_icon_qc3nm3.png"
              className={styles.googleIcon}
            />
            Sign in with Google
          </button>

          )
          
          <p onClick={toggleLoginClick}>
  {signUp ? "Already have an account? Sign in" : "Don't you have an account? Sign up"}
</p>

        </div>
        <div className={styles.imgContainer}>
          <img
            src="https://res.cloudinary.com/dqgvmwnpl/image/upload/v1706104224/E-Learning/phone-with-music-icon-headphones-blurred-background-music-listening-concept-copy-space_pryqvb.jpg"
            alt=""
          />
        </div>
      </div>
    </>
  );
}
